name = "ESAFunctions"
uuid = "f2ae3dbe-0e69-47a0-a214-cb9e16550311"
authors = ["Natapon Wanapinit"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
